<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DBetter.TrainCompositions.Application\DBetter.TrainCompositions.Application.csproj" />
      <ProjectReference Include="..\DBetter.TrainCompositions.Domain\DBetter.TrainCompositions.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
      <PackageReference Include="Zwergenland.CleanMessageBus.RabbitMQ" Version="1.2.1" />
    </ItemGroup>

</Project>
