// <auto-generated />
using System;
using DBetter.TrainCompositions.Infrastructure.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBetter.TrainCompositions.Infrastructure.Migrations
{
    [DbContext(typeof(DBetterContext))]
    [Migration("20260510170858_PlannedFormation")]
    partial class PlannedFormation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBetter.TrainCompositions.Infrastructure.CoachLayouts.CoachLayoutPersistenceDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConstructionType")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("CoachLayouts", (string)null);
                });

            modelBuilder.Entity("DBetter.TrainCompositions.Infrastructure.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("DBetter.TrainCompositions.Infrastructure.PlannedFormations.PlannedFormationPersistenceDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachSequenceHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReverseCoachSequenceHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachSequenceHash")
                        .IsUnique();

                    b.HasIndex("ReverseCoachSequenceHash")
                        .IsUnique();

                    b.ToTable("PlannedFormations", (string)null);
                });

            modelBuilder.Entity("DBetter.TrainCompositions.Infrastructure.PlannedFormations.PlannedFormationPersistenceDto", b =>
                {
                    b.OwnsMany("DBetter.TrainCompositions.Infrastructure.PlannedFormations.PlannedCoachPersistenceDto", "CoachSequence", b1 =>
                        {
                            b1.Property<Guid>("PlannedFormationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("LayoutId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Position")
                                .HasColumnType("smallint");

                            b1.HasKey("PlannedFormationId", "Id");

                            b1.HasIndex("PlannedFormationId", "Position");

                            b1.ToTable("PlannedCoaches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlannedFormationId");
                        });

                    b.Navigation("CoachSequence");
                });
#pragma warning restore 612, 618
        }
    }
}
