<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Zwergenland.CleanDomainValidation" Version="1.2.0-pre1" />
      <PackageReference Include="Zwergenland.CleanMediator" Version="1.1.1" />
      <PackageReference Include="Zwergenland.CleanMessageBus.Abstractions" Version="1.2.1" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="DBetter.TrainCompositions.Infrastructure"/>
        <InternalsVisibleTo Include="DBetter.TrainCompositions.Infrastructure.Tests"/>
        <InternalsVisibleTo Include="DBetter.TrainCompositions.Domain.Tests"/>
    </ItemGroup>

</Project>
